version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - db
    networks:
      - app_network

  db:
    image: mariadb:10.6
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: performance_db
    ports:
      - "3306:3306"
    networks:
      - app_network
    volumes:
      - db_data:/var/lib/mysql

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - app_network
  
  mariadb_exporter:
    image: prom/mysqld-exporter:latest
    environment:
      - DATA_SOURCE_NAME=root:password@tcp(db:3306)/information_schema
    command: 
     - --config.my-cnf=/cfg/.my.cnf
    volumes:
      - ./cfg/.my.cnf:/cfg/.my.cnf
    ports:
      - "9104:9104"
    networks:
      - app_network
    depends_on:
      - db
  
  grafana:
    image: grafana/grafana:latest
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin  # Set admin password
    networks:
      - app_network
    ports:
      - "3000:3000"
    depends_on:
      - prometheus

networks:
  app_network:
    driver: bridge

volumes:
  db_data:
