global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "flask_app"
    static_configs:
      - targets: ["app:5000"]
  
  - job_name: 'mariadb'
    static_configs:
      - targets: ['mariadb_exporter:9104']

